version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: AuthenticationApi.Solution/AuthenticationApi.Presentation/Dockerfile
    ports:
      - "5000:5000" # Mapea el puerto 5000 del host al puerto 80 del contenedor
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
    networks:
      - my_network
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Lancort20+12"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql 
    networks:
      - my_network

  tests:
    build:
      context: .
      dockerfile: AuthenticationApi.Solution/UnitTest.AuthenticationApi/Dockerfile
    depends_on:
      - sqlserver
    volumes:
      - ./TestResults:/src/AuthenticationApi.Solution/UnitTest.AuthenticationApi/TestResults # Guarda resultados
    entrypoint: >
      sh -c "
      dotnet test --logger:trx
      "
networks:
  my_network:
    driver: bridge

volumes:
  sqlvolume: